---
#
# Ansible managed
#
repository:
  description: Install and configure unowned_files on your system.
  homepage: https://robertdebock.nl/
  topics: unownedfiles, security, ansible, molecule, playbook
